### ISSUE TITLE
custom conversion (face detection)

### ISSUE THREAD

**Issue by vesper8** [spatie/laravel-medialibrary#781] opened 2017-10-08 00:40 UTC
I currently have some methods that run a Face Detection algorithm on an image, which grabs the face and crops it

I would like for this to run whenever a new image is loaded, ideally I would have liked to run this using this package's Media Conversions

Is there a way to define a custom media conversion that runs arbitrary code ?

**Comment by freekmurze** [comment] 2017-10-08 06:31
For this to work we could introduce a new `ConversionWillStart` event much like the already implemented [`ConversionHasBeenCompleted` event](https://docs.spatie.be/laravel-medialibrary/v6/advanced-usage/consuming-events#conversionhasbeencompleted) 

Inside that `ConversionWillStartEvent` you could write the results of your Face detection to the `manipulations` attribute of a `Media` instance. More info on that here: https://docs.spatie.be/laravel-medialibrary/v6/advanced-usage/storing-media-specific-manipulations

 I'd accept a fully tested PR that adds the `ConversionWillStart` event to this package.

**Comment by huglester** [comment] 2017-10-11 10:27
hello @vesper8 
May I ask you offtopic, what library do you use for face detection?

**Comment by vesper8** [comment] 2017-10-11 20:23
there are quite many to choose from.. i can't remember why I picked this one but I've been using it and it works well enough https://github.com/softon/laravel-face-detect

**Comment by huglester** [comment] 2017-10-12 12:38
Thank you for information :)

**Comment by AlexVanderbist** [comment] 2017-10-17 07:57
@vesper8 did the `ConversionWillStart` event work out for you? 

Can this issue be closed?

**Comment by freekmurze** [comment] 2017-10-17 08:16
Closing for now, reopen if this is still a problem.

**Closed by freekmurze** 2017-10-17 08:16 UTC
Labels: enhancement, help wanted

**Comment by vesper8** [comment] 2017-10-17 13:34
I have a conversion named 'optimized' and what I'm doing now is I'm piggy-backing off of it like so

```
class FaceDetector
{
    use QueueOutput;

    /**
     * @param \Spatie\MediaLibrary\Events\MediaHasBeenAdded $event
     */
    public function handle(ConversionHasBeenCompleted $event)
    {
        $media = $event->media;
        $conversion = $event->conversion;

        if ($conversion->getName() == "optimized") {
            dispatch(new \App\Jobs\DetectFace($media));
        }
    }
}
```

Unfortunately it doesn't allow me to do `$media->getMedia('face')` so it's not perfect..

I got confused about your proposed solution. First, I'm confused about the purpose of writing manipulations in the database as described in the docs here

```
// Add a width filter to the 'thumb' manipulations
$mediaItems = $newsItem->getMedia('images');
$mediaItems[0]->manipulations = ['thumb' => [ 'width' => '10']];

// This will cause the thumb conversion to be regenerated
$mediaItems[0]->save();
```

I define all my conversions in my model.. is it just a matter of preference?

Second, I'm confused how to define a "dummy" conversion that doesn't actually have any manipulations.

As it stands.. by piggybacking off of another conversion, my folders all have a face.jpg in them. But now I would like to be able to do $media->getPath('face'). But as understand in order for that to work I'd need a dummy conversion named 'face' in my model. How can I add that?

**Comment by AlexVanderbist** [comment] 2017-10-18 07:28
Hey @vesper8 

You're already piggybacking off of the `optimized` conversion. This means you can do something like `$media->getPath('optimized')`. If you would rename your dummy `optimized` conversion to `face` you can simple `$media->getPath('face')` as intended. Let me know if this works out or if I'm missing anything obvious.

**Comment by vesper8** [comment] 2017-10-18 12:45
hehe sorry if this is so obvious.. but i want to keep my optimized conversion! I use it

```
        $this->addMediaConversion('optimized')
            ->fit(Manipulations::FIT_MAX, 1000, 1000)
            ->queued();
```

but what I think you're proposing is that.. I create another conversion identical to the 'optimized' conversion, and call it 'face'.. and piggy back off of that one? and then what? allow for the normal conversion to create the file 'face.jpg', and THEN execute my face detection with the ConversionHasBeenCompleted.. and.. replace the file.jpg with the results of the face detection?

do you see what I'm not understanding? this seems redundant

I would prefer a scenario where I don't have to do a "fake conversion"

**Comment by AlexVanderbist** [comment] 2017-10-18 15:52
@vesper8 I see your point on not having to create a "fake conversion". Ideally you would be able to define custom image manipulations but that's not implemented yet. 

>but what I think you're proposing is that.. I create another conversion identical to the 'optimized' conversion, and call it 'face'.. and piggy back off of that one? and then what? allow for the normal conversion to create the file 'face.jpg', and THEN execute my face detection with the ConversionHasBeenCompleted.. and.. replace the file.jpg with the results of the face detection?

Exactly. You'd replace the `face.jpg` conversion file with the result of the face detection. This way `->getPath('face')` with simply return the path to `face.jpg` (which will be your custom file). 

I totally agree that this seems a bit redundant. If you can figure out a clean and tested way to do this feel free to open a PR!

**Comment by vesper8** [comment] 2017-10-21 03:37
@AlexVanderbist 

I just found this in the docs https://docs.spatie.be/laravel-medialibrary/v6/converting-other-file-types/creating-a-custom-image-generator#creating-a-custom-image-generator

Couldn't I use this instead?

**Comment by Vusys** [comment] 2019-08-23 10:30
For an application I'm working on we need to use Intervention's image package for adding an image conversion.

I've found two ways to do it, but neither seem especially ideal.

Both require adding an empty conversion:

```php
// FooModel.php

public function registerMediaConversions(Media $media = null): void
{
    $this->addMediaConversion('watermarked')->keepOriginalImageFormat();
}
```

The first solution is to piggy back off the `MediaHasBeenAdded` event. Register a listener and you can pull the converted file from storage, do something with it, then reupload it:

```php
public function handle(ConversionHasBeenCompleted $event)
{
    if ($event->conversion->getName() !== 'watermarked') {
        return;
    }

    $path = $event->media->getPath('watermarked');

    // Get the image from storage
	 $image = $this->storage->disk($event->media->disk)->get($path)
	
    // @TODO Do something with image

    // Put it back in storage
    $this->storage->disk($event->media->disk)->put($path, $image);
}
```

Pros: 

* Doesn't touch any Media Library internals

Cons:

* The image that needs manipulating gets a trip to S3 (or whatever storage you use), then a trip back, then converted, then uploaded again...

---

The second solution is to extend the image file type class and do something in the `convert` method.

In the config, replace the Image class with an extension:

```php
//...
    /*
     * These generators will be used to create an image of media files.
     */
    'image_generators' => [
        //Spatie\MediaLibrary\ImageGenerators\FileTypes\Image::class,
        \App\Spatie\MediaLibrary\ImageFileType::class,
        Spatie\MediaLibrary\ImageGenerators\FileTypes\Webp::class,
        Spatie\MediaLibrary\ImageGenerators\FileTypes\Pdf::class,
        Spatie\MediaLibrary\ImageGenerators\FileTypes\Svg::class,
        Spatie\MediaLibrary\ImageGenerators\FileTypes\Video::class,
    ],
//...
```
	
Do something in the `convert` method:

```php
class ImageFileType extends Image
{
    public function convert(string $path, Conversion $conversion = null): string
    {
        if ($conversion->getName() !== 'watermarked') {
            return $path;
        }

	     $image = $path;
	
  		// @TODO: Do something with the image
  
       // Save the image to a tmp file in the same directory as the other conversions
       $tmpPath = pathinfo($path, PATHINFO_DIRNAME) . '/' . Str::random() . '.' . pathinfo($path, PATHINFO_EXTENSION);

        \File::put($tmpPath, $image);
     
        // Return that path
        return $tmpPath;
    }
}    
```

Pros: 

* No back and forth between storage

Cons: 

* Touches more of Media Library's internals 
* May have other breakages I'm not aware of

---

Unfortunately the `ConversionWillStart` event doesn't seem all that useful here. It fires before the conversions, but has no way to influence them.

A possible third solution would be to be able to add a custom manipulation in `Manipulations` that says defer to this external code, then have that called during `FileManipulator::performManipulations`.

To do that right now, I think I'd need to extend the  `Manipulations` class to support a new manipulation, and extend `FileManipulator` to be able route into that external code instead of the `Image` class.

Curious to see if anyone has had better ideas and what the Spatie folk think is the better solution.

**Comment by AlejandroAkbal** [comment] 2022-05-30 21:32
Hey @Vusys, did you manage to implement a robust solution?
