### ISSUE TITLE
Media::all() always return empty

### ISSUE THREAD

**Issue by musiwei** [spatie/laravel-medialibrary#2812] opened 2022-02-28 06:46 UTC
```php
use Spatie\MediaLibrary\MediaCollections\Models\Media;
... 
public function fnInController(){
return Media::all();
}
```

Version: "spatie/laravel-medialibrary": "10.1.1"

Database is filled with valid records. However, the result is always empty. Query builder doesn't work neither.

**Comment by freekmurze** [comment] 2022-02-28 06:49
Duplicate of discussion

**Closed** 2022-02-28 06:49 UTC
