### ISSUE TITLE
While deleting a media, unlink('public/storage/1/conversion/{Name}') permission denied. error comes.

### ISSUE THREAD

**Issue by manishsahani999** [spatie/laravel-medialibrary#1328] opened 2018-12-08 12:46 UTC
when deleting the media the error comes for conversions only.  and the conversions are not deleting, 
everything works fine in windows but on Linux, it is throwing errors.

**Comment by thanhtutoo** [comment] 2019-02-07 18:18
I am also facing this problem, any solution ?

**Comment by acodeninja** [comment] 2019-02-12 10:14
Is the process that does the conversions running as a different user from the process that is serving your application? In my setup, I have supervisord running conversions and php7.2-fpm serving the site itself. Both processes run as the www-data user (usual for Ubuntu, etc).

If you have configured the processes to run under different users this may cause the issue, as the process that is trying to delete the conversions doesn't have permission to delete them (as they were created by a different user).

**Comment by atymic** [comment] 2019-06-01 07:44
As Ninja said, it's almost certainly a permissions issue due to queues. If you are still having the issue, can you compare the permissions of files created by the app directly with the converted files (using `ls -li`)?

**Comment by brendt** [comment] 2019-07-15 07:47
Looks indeed like a permissions error. I'll be closing this issue. Feel free to still reply if anything new comes up.

**Closed by brendt** 2019-07-15 07:47 UTC

**Comment by S-DICKSON** [comment] 2022-02-17 08:40
I was facing this problem too and it was caused by my systemctl service that was running the Laravel queue for my development environment.

**The culprit.** 
``
[Unit]
Description=Runs and keeps alive the artisan queue:work process


[Service]
Restart=always
WorkingDirectory=/home/s-dickson/Sites/dashboard.groundwow
ExecStart=/usr/bin/php artisan queue:work --queue=high,default

[Install]
WantedBy=default.target
``

**Solution**
I had to stop the systemctl service and run the queue manually. I'll try to find a solution to my systemctl service and post it back in this thread if anyone has the same issue in the future.

Thanks, @acodeninja for helping me work out what the problem was!

**Comment by S-DICKSON** [comment] 2022-02-21 07:35
I was facing this problem too and it was caused by my systemctl service that was running the Laravel queue for my development environment.

**The culprit.** 
```
[Unit]
Description=Runs and keeps alive the artisan queue:work process


[Service]
Restart=always
WorkingDirectory=/laravel-project
ExecStart=/usr/bin/php artisan queue:work --queue=high,default

[Install]
WantedBy=default.target
```

**Solution**
I had to stop the systemctl service and run the queue manually. I'll try to find a solution to my systemctl service and post it back in this thread if anyone has the same issue in the future.

Thanks, @acodeninja for helping me work out what the problem was!
