### ISSUE TITLE
Storage path is not part of public path

### ISSUE THREAD

**Issue by Ruriko** [spatie/laravel-medialibrary#2709] opened 2021-12-19 22:18 UTC
### Discussed in https://github.com/spatie/laravel-medialibrary/discussions/2708

<div type='discussions-op-text'>

<sup>Originally posted by **Ruriko** December 19, 2021</sup>
I'm running on Ubuntu 20.04, php7.4 and nginx as my webserver. I get this error:
> Storage path `/var/www/type.adoreanime.com/htdocs/Linkati/storage/app` is not part of public path `/var/www/type.adoreanime.com/htdocs/Linkati/public` (View: /var/www/type.adoreanime.com/htdocs/Linkati/resources/views/layouts/master.blade.php) (View: /var/www/type.adoreanime.com/htdocs/Linkati/resources/views/layouts/master.blade.php) (View: /var/www/type.adoreanime.com/htdocs/Linkati/resources/views/layouts/master.blade.php)

I've already ran `php artisan storage:link` but I still get the error.
This is my filesystems.php

```
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Filesystem Disk
    |--------------------------------------------------------------------------
    |
    | Here you may specify the default filesystem disk that should be used
    | by the framework. The "local" disk, as well as a variety of cloud
    | based disks are available to your application. Just store away!
    |
    */

    'default' => env('FILESYSTEM_DRIVER', 'local'),

    /*
    |--------------------------------------------------------------------------
    | Default Cloud Filesystem Disk
    |--------------------------------------------------------------------------
    |
    | Many applications store files both locally and in the cloud. For this
    | reason, you may specify a default "cloud" driver here. This driver
    | will be bound as the Cloud disk implementation in the container.
    |
    */

    'cloud' => env('FILESYSTEM_CLOUD', 's3'),

    /*
    |--------------------------------------------------------------------------
    | Filesystem Disks
    |--------------------------------------------------------------------------
    |
    | Here you may configure as many filesystem "disks" as you wish, and you
    | may even configure multiple disks of the same driver. Defaults have
    | been setup for each driver as an example of the required options.
    |
    | Supported Drivers: "local", "ftp", "sftp", "s3", "rackspace"
    |
    */

    'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL') . '/storage',
            'visibility' => 'public',
        ],

        's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
        ],

        's3_public' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
            'visibility' => 'public',
        ],

    ],

];
```</div>

**Comment by freekmurze** [comment] 2022-01-19 07:57
Duplicate of a discussion.

**Closed by freekmurze** 2022-01-19 07:57 UTC
