### ISSUE TITLE
Media conversation does not working on me!!!

### ISSUE THREAD

**Issue by theperfectcoder** [spatie/laravel-medialibrary#2982] opened 2022-07-15 09:57 UTC
Hi guys, I have a problem with media conversation, I added registerMediaConversions() in my model but its not working (im using latest version )

here is my table generated by spatie (p.s. I can change my table because there is important medias from production)
```
Schema::create('media', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('model_id');
            $table->string('model_type');
            $table->char('uuid')->unique()->nullable();
            $table->string('collection_name');
            $table->string('name');
            $table->string('file_name');
            $table->string('mime_type')->nullable();
            $table->string('disk');
            $table->string('conversions_disk')->nullable();
            $table->longText('manipulations');
            $table->longText('custom_properties');
            $table->longText('generated_conversions');
            $table->longText('responsive_images');
            $table->integer('size');
            $table->integer('order_column')->nullable();
            $table->timestamps();
        });
```

and here is my model

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Spatie\Image\Exceptions\InvalidManipulation;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media as SpatieMedia;


class LendingSetting extends Model implements HasMedia
{
    use InteractsWithMedia;

    /**
     * @var string[]
     */
    protected $casts = [
        'branding' => 'array',
        'menu' => 'array',
        'socials' => 'array',
        'reviews' => 'array',
        'advanced' => 'array',
        'current_banner' => 'array',
        'rooms' => 'array',
        'order' => 'array',
        'order_form' => 'array',
        'pwa'=>'array'
    ];

    /**
     * @var array
     */
    protected $guarded = [];

    /**
     * @param SpatieMedia|null $media
     * @return void
     */
    public function registerMediaConversions(SpatieMedia $media = null): void
    {
        try {
            $this->addMediaConversion('thumb')
                ->width(500)
                ->height(500);
        } catch (InvalidManipulation $e) {
            dd($e->getMessage());
        }
    }

    /**
     * @return BelongsTo
     */
    public function hotel(): BelongsTo
    {
        return $this->belongsTo(Hotel::class, 'hotel_id', 'id');
    }

    /**
     * @return MorphMany
     */
    public function medias(): MorphMany
    {
        return $this->morphMany(Media::class, 'model');
    }

    /**
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        static::deleting(function($model) { // before delete() method call this
            $model->medias()->each(function($topic){
                $topic->delete();
            });
        });
    }

}


```
    
    
    and my route method
    
   ```
Route::post('/test-image', function (Request $request) {
    if ($request->has('image')) {
        $lendingSetting = \App\Models\LendingSetting::where('id', $request->lending_settings_id)->first();
        $extension = $request->image->extension();
        $image = $lendingSetting->addMedia($request->image)
            ->usingFileName(Str::uuid() . '.' . $extension)
            ->toMediaCollection('image');
        return response()->json($image->getFullUrl());
    } else {
        return null;
    }
});
```

Please any help

**Comment by parallels999** [comment] 2022-07-20 14:00
Duplicate of #2981

**Closed** 2022-07-29 10:05 UTC
