### ISSUE TITLE
Filesystem GetStream adds extra /

### ISSUE THREAD

**Issue by afolabiabass** [spatie/laravel-medialibrary#3194] opened 2023-02-24 07:51 UTC
When attempting to download multiple files the stream is unable to find the file because of an extra / in the file path  from 

`        $sourceFile = $this->getMediaDirectory($media).'/'.$media->file_name;` [here](https://github.com/spatie/laravel-medialibrary/blob/d42ef44607527aa9196b3e9eaf691c22ea5e4ff0/src/MediaCollections/Filesystem.php#L199) 

This method is inconsistent with how we get the path in other parts of the repository such as on line 61 on the same file. 

Please let me know if you are able to replicate the issue. It is important to note that I have a custom PathGenerator with the same getPath function as the DefaultPathGenerator which is the primary function used in the getMediaDirectory called in the GetStream when traced down.

I am happy to create a PR for a fix if you can confirm it is an issue. I am currently working around this issue by overriding the FileSystem class in a service provider.

**Comment by parallels999** [comment] 2023-02-24 16:56
Looks like a bug to me

**Comment by freekmurze** [comment] 2023-06-29 07:22
Closing as it is not reproducible.

**Closed by freekmurze** 2023-06-29 07:22 UTC
Labels: needs-research, needs-more-info
