### ISSUE TITLE
WebP responsive images

### ISSUE THREAD

**Issue by veneliniliev** [spatie/laravel-medialibrary#3081] opened 2022-11-04 07:51 UTC
when a **webp** image is added no **wepb** responsive images are generated for `media_library_original`

the problem may be here:
`if ($this->generateResponsiveImages && (new ImageGenerator())->canConvert($media)) {`

`use Spatie\MediaLibrary\Conversions\ImageGenerators\Image as ImageGenerator;`
**ImageGenerator** instance always is an `Image` conversion and returns `false` for **webp** images

is there a way to have responsive images in **webp** format?

for the moment I run the job (_GenerateResponsiveImagesJob_) manually but it is not a good solution :(

**Comment by patinthehat** [comment] 2022-11-22 12:56
@veneliniliev Would it be possible to provide a failing unit test to show that this is in fact a bug, or possibly a sample project/repository that demonstrates the issue described? Thanks!

**Comment by yannkuesthardt** [comment] 2022-12-23 10:57
Can confirm this issue. In the file "FileAdder.php" (Spatie\MediaLibrary\MediaCollections) in the function "processMediaItem" the following if statement is used to check if the file can be made responsive (this is used whenever "->toMediaCollection()" is called on a new image). 

`if ($this->generateResponsiveImages && (new ImageGenerator())->canConvert($media)) {`

The problem is, that ImageGenerator is a renamed import for
`Spatie\MediaLibrary\Conversions\ImageGenerators\Image`
which will of course return false when passing a **.webp** file to
 `canConvert()`
 
 My suggestion for a simple fix is changing the if statement to the following
 `if ($this->generateResponsiveImages && ((new ImageGenerator())->canConvert($media) || (new WebpGenerator())->canConvert($media))) {`
 where "WebpGenerator" is a renamed import for
 `use Spatie\MediaLibrary\Conversions\ImageGenerators\Webp`

**Comment by freekmurze** [comment] 2022-12-24 11:51
Could you PR that change and add a test to prove that it works?

**Comment by yannkuesthardt** [comment] 2022-12-25 12:06
I will do that, but I won’t have time till mid/end January

**Comment by stuartcusackie** [comment] 2023-01-16 13:36
Also seeing this issue. By the way, manually running he GenerateResponsiveImagesJob doesn't work for me. Responsive variants are generated but they are using the original format of the image.

**Comment by websitevirtuoso** [comment] 2023-04-10 04:06
I also have problem with this.
![image](https://user-images.githubusercontent.com/5112918/230823685-64be4a81-f225-417d-b3cd-d72e3708c6ae.png)

Last image it webp and lib couldn't create responsive images

**Comment by websitevirtuoso** [comment] 2023-04-10 04:15
Ok I found the problem. Here details
![image](https://user-images.githubusercontent.com/5112918/230824417-ef03101f-24f5-41e8-952b-51215636f42f.png)

In class Spatie\MediaLibrary\Conversions\ImageGenerators
we have 2 functions "supportedExtensions", "supportedMimeTypes" in this we have list of extensions which we can process. Just add "webp" extension and it will work.
![image](https://user-images.githubusercontent.com/5112918/230824569-a5033426-86a5-43ab-b60f-a06c0d492bda.png)

I can create PR if this is works but don't want to write tests=) and deep dive into details. For my self, I could create a patch for this file

**Comment by freekmurze** [comment] 2023-04-12 08:33
Ok, PR the addition of webp there 👍

**Comment by websitevirtuoso** [comment] 2023-06-17 00:28
it can be closed. because PR already merged and we have new version

**Closed** 2023-06-17 21:48 UTC
Labels: needs-research, awaiting-response
