### ISSUE TITLE
HTTP 404 not found when trying to download via the file path

### ISSUE THREAD

**Issue by humaneguy** [spatie/laravel-medialibrary#2882] opened 2022-04-13 14:18 UTC
### Discussed in https://github.com/spatie/laravel-medialibrary/discussions/2881

<div type='discussions-op-text'>

<sup>Originally posted by **humaneguy** April 13, 2022</sup>
Hi I have a frontend for downloading reports generated by admins.

So when the download button is clicked, it should download the file for the administrator.

I'm rendering it on the frontend using this code:

```blade
<a href="{{ $download->getPath() }}" class="btn btn-sm btn-white d-none d-md-inline-block">Download</a>
```

**Comment by freekmurze** [comment] 2022-04-13 16:14
Duplicate of discussion

**Closed by freekmurze** 2022-04-13 16:14 UTC
