### ISSUE TITLE
9.11.4 introduces error when deleting file from S3 bucket

### ISSUE THREAD

**Issue by vesper8** [spatie/laravel-medialibrary#2816] opened 2022-03-01 19:45 UTC
Just tested reverting back to `9.11.3` and I get no errors. I only get this error as of `9.11.4`.

All my images are on a S3 bucket. When I try to delete an image, works perfectly on `9.11.3`, on `9.11.4` I get this error:

```

Error executing "DeleteObjects" on "https://redacted.s3.eu-central-1.amazonaws.com/?delete"; AWS HTTP error: Client error: `POST https://redacted.s3.eu-central-1.amazonaws.com/?delete` resulted in a `400 Bad Request` response:	
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>Missing required header for this reque (truncated...)
InvalidRequest (client): Missing required header for this request: Content-MD5 OR x-amz-checksum-* - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>Missing required header for this request: Content-MD5 OR x-amz-checksum-*</Message>
```

The database record gets deleted, but the files don't get deleted on S3 and I get two errors like the one above.

Not sure what's going on, the change in `9.11.4` seems harmless at first glance although I don't understand them. But I can confirm 100% this is working in `9.11.3` and broken in `9.11.4`

pinging @ziming since he authored the PR from `9.11.4`

**Comment by ziming** [comment] 2022-03-02 01:53
I would say my PR is not the 1 causing this issue. because 1 of my sites havent update to this version and I already get delete from S3 error.

**Comment by vesper8** [comment] 2022-03-02 04:14
@ziming I get the error 100% of the time with 9.11.4 and I get the error 0% of the time on 9.11.3.

I mean I haven't done thousands of tests but I have done more than a dozen.

I do have this on my User model which is the one model that uses media

```

    public function shouldDeletePreservingMedia(): bool
    {
        return true;
    }
```

When I delete the media I just do `$media->delete();`


And this has always deleted the media on S3 prior to this new error.


I'm not blaming your PR specifically, I don't know if something else happened with the release of `9.11.4`, just pointing out what I'm observing.

**Comment by ziming** [comment] 2022-03-02 05:51
Hmm interesting. when i find something new i update here.

**Comment by sebastiaanluca** [comment] 2022-03-03 14:04
We got 26 identical exceptions since deploying the upgrade.

We do something like this to delete existing media individually:
```php
return $this->getMedia($collection)
            ->each->delete();
```

The `/?delete` endpoint seems wrong to me at first glance, unless the data like ID is in the payload. Perhaps `forceDelete()` does things differently?

**Comment by ziming** [comment] 2022-03-03 14:15
Do you use soft deletes sebastiaan?

**Comment by sebastiaanluca** [comment] 2022-03-03 14:22
> Do you use soft deletes sebastiaan?

Not for the media itself, but we do for the model it's related to.

**Comment by sebastiaanluca** [comment] 2022-03-03 15:14
After some digging around, this seems to be an `aws/aws-sdk-php` bug introduced in v3.209.31.

- https://github.com/aws/aws-sdk-php/issues/2389
- https://github.com/aws/aws-sdk-php/pull/2390

You can check which version you use with `composer show -i`.

v3.211.x should have fixed it, though not sure how to update that since we don't use it directly.

**Comment by ziming** [comment] 2022-07-03 13:31
@vesper8 or @freekmurze 

Could 1 of you close this issue? it's been long confirmed since 3rd March that it is a bug introduced in aws/aws-sdk-php and not my commit.

**Closed** 2022-07-03 21:11 UTC
