### ISSUE TITLE
The 'format' manipulation of the conversions is not stored in the database.

### ISSUE THREAD

**Issue by joserick** [spatie/laravel-medialibrary#3153] opened 2023-01-09 21:23 UTC
Hi,

I'm trying to get the conversion url with previously configured png extension, but apparently it doesn't store the format manipulation in the database, so the system returns the url in jpg.

Version laravel-medialibrary: 10.7.8

### Configuration and Application:
```php
$this->addMediaCollection('cover_app')->singleFile()
   ->registerMediaConversions(function (Media $media) {
        ...
        $this->addMediaConversion('medium')
            ->format(Manipulations::FORMAT_PNG) // <- Format to apply
            ->width(350)
            ->height(350);
    });
....

Category::find(11)->addMedial($file)->toMediaCollection('cover_app');
```
### Model Media
I see that the format for the conversion specified in the "manipulations" column is not stored
```php
Spatie\MediaLibrary\MediaCollections\Models\Media {#4255
  ...
  file_name: "A2XVdlYYp14wfBLCBRQqZEQTozTixq.png",
  mime_type: "image/png",
  ...
  manipulations: "[]", // <- Not manipulation format for 'medium' conversion
  custom_properties: "[]",
  generated_conversions: "{"thumb": true, "medium": true}",
  ...
}
```
### Get conversion url
```php
Category::find(11)->getFirstMediaUrl('cover_app', 'medium');
// Return .../137/conversions/A2XVdlYYp14wfBLCBRQqZEQTozTixq-medium.jpg <- Incorrect format
```
Return the conversion in JPG  .../137/conversions/A2XVdlYYp14wfBLCBRQqZEQTozTixq-medium.jpg

**But** the conversion in PNG does exist .../137/conversions/A2XVdlYYp14wfBLCBRQqZEQTozTixq-medium.png 

![Captura desde 2023-01-09 15-01-44](https://user-images.githubusercontent.com/15143699/211407794-b3876448-db67-48fa-bd7b-c3014dd7f45c.png)

### In /src/Conversions/Conversion.php expect to get the manipulation format but this does not exist in the database
```php
public function getResultExtension(string $originalFileExtension = ''): string
{
    ....
    if ($manipulationArgument = $this->manipulations->getManipulationArgument('format')) {
        return $manipulationArgument;
    }

    return $originalFileExtension;
}
```
I am not clear at what moment the manipulation of the 'format' is stored but it is not being carried out.

**Comment by timvandijck** [comment] 2023-03-03 14:51
@joserick It is indeed odd that you receive the jpg instead of the png in your example. Sadly I don't seem to be able to replicate your problem.

I noticed that you only define a [conversion](https://spatie.be/docs/laravel-medialibrary/v10/converting-images/defining-conversions) and not a [manipulation](https://spatie.be/docs/laravel-medialibrary/v10/advanced-usage/storing-media-specific-manipulations). Note that these are two different things. Therefore it's not wrong that the manipulations array is empty.

As for storing the extension, this is not something that is intended to be persisted in the database. 

If possible please provide a replicatable example, preferable in the form of a failing test.

**Comment by freekmurze** [comment] 2023-06-29 07:21
Closing as it is not reproducible.

**Closed by freekmurze** 2023-06-29 07:21 UTC
Labels: needs-more-info

**Comment by satoved** [comment] 2024-04-27 18:03
Had a very similar issue, maybe my solution would come in handy to somebody.

My initial set up was:
```
        $this->addMediaCollection('logo')->singleFile()->registerMediaConversions(function (Media $media) {
            $this->addMediaConversion('**thumb**')->fit(Fit::Fill, 100, 100)->background('#fff');
        });

        $this->addMediaCollection('logo_big')->singleFile()->registerMediaConversions(function (Media $media) {
            $this->addMediaConversion('**thumb**')->fit(Fit::Contain, 400, 400)->keepOriginalImageFormat();
        });
```

It then generates broken jpg links for logo_big collection.

It turned out that something gets messed up when I use conversions of the same name on different collections, though it seems intuitive.

The fix was to rename one of the conversions:

```
        $this->addMediaCollection('logo')->singleFile()->registerMediaConversions(function (Media $media) {
            $this->addMediaConversion('thumb')->fit(Fit::Fill, 100, 100)->background('#fff');
        });

        $this->addMediaCollection('logo_big')->singleFile()->registerMediaConversions(function (Media $media) {
            $this->addMediaConversion('**thumb_big**')->fit(Fit::Contain, 400, 400)->keepOriginalImageFormat();
        });
```
