### ISSUE TITLE
Unable to decode image from file error, introduced since 6.2.1

### ISSUE THREAD

**Issue by oad-dwarf** [spatie/laravel-medialibrary#812] opened 2017-10-24 14:39 UTC
This change:

https://github.com/spatie/laravel-medialibrary/compare/6.2.0...6.2.1

.. broke media conversions for me as I updated spatie/laravel-medialibrary from a version before 6.2.1. 

I get this error:

Intervention\Image\Exception\NotReadableException
Unable to decode image from file (/tmp/GlideBKMlDI).

When I look at the temp file, I see that it is consistently shorter than the original file.

I was able to fix it by changing be fread() to fgets(). Why it makes a difference I have no clue. It doesn't seem right to use fgets() for binary data :-)

The environment is alpine linux 3.6 and php 7.1 with nginx and fpm.

**Comment by AlexVanderbist** [comment] 2017-11-03 10:47
That's really strange... I tried to reproduce this issue but couldn't seem to make anything break. 

Does this happen with all images? Can you try this with a regular text file?

**Comment by oad-dwarf** [comment] 2017-11-06 11:39
It happened with a 616696 bytes png file.

**Comment by freekmurze** [comment] 2018-02-09 23:50
Is this still a problem in the latest version of the package?

**Comment by MartinJac** [comment] 2018-02-11 02:13
@freekmurze unsure about @oad-dwarf, but I've been able to replicate this when using s3.

Changing from fread() to fgets() resolved the issue (Windows).

**Comment by freekmurze** [comment] 2018-03-21 11:13
Closing because we can't reproduce it.

**Closed by freekmurze** 2018-03-21 11:13 UTC

**Comment by tobz-nz** [comment] 2018-05-09 23:11
@oad-dwarf Did you figure this one out? I'm getting the same issue. Also Alpine-Linux. (in a K8 setup)

**Comment by simioluwatomi** [comment] 2018-06-27 22:44
I have been getting this error on all PNG images when uploading to s3. Very weird. Uploads are being performed with `addMediaFromBase64`

**Comment by tobz-nz** [comment] 2018-06-27 22:45
I think its an Alpine issue. We swapped to an Ubuntu image(no other changes) and all working perfectly now.

**Comment by oad-dwarf** [comment] 2018-07-02 11:11
@tobz-nz No I still have my patch in place. Haven't tested since then if the problem is still there. Perhaps I'll check it again when we switch to Alpine 3.8 and PHP 7.2

**Comment by Aryan1** [comment] 2018-08-13 07:25
Having same issue, the original image is uploaded successfully but conversions simply fails for all png files when using s3 driver, same error as mentioned above.

on Windows + PHP 7.2.8

**Comment by ShinHyungJune** [comment] 2018-11-22 09:36
Having same issue Too T.T
when using s3 driver, same error as mentioned above.

on Windows + PHP 7.1.2

**Comment by skalero01** [comment] 2019-04-03 23:51
I receive also the error on S3 with any image. Will check further to see why is happening

**Comment by skalero01** [comment] 2019-04-06 20:43
Hi, i was testing for a whole day and apparently this error happens only when the filesystem is set with S3, i tried with the "media" filesystem (as you can see on the readme of laravel-medialibrary) and there all worked perfectly.

So i still dont understand why the error happens but the solution i did was to work with the media filesystem and run a command that moves all the files from media to the s3 filesystems.

And worked great, you can see the code for the command on here to implement it yourself: https://gist.github.com/skalero01/fffb760e818c5a6b1adb899dfd534c58

**Comment by victor-priceputu** [comment] 2019-06-07 15:26
I am getting the same issue, package version `7.6.0`, php `7.3.6` using homestead and `local` as the driver.
`Intervention\Image\Exception\NotReadableException : Unable to read image from path (/tmp/GlideoH2Jh8).`
`Caused by
 ImagickException: no decode delegate for this image format `' @ error/constitute.c/ReadImage/504
 `
This happens only when trying to add a file in tests, using fake files.

**Comment by Daniyal-Javani** [comment] 2019-07-21 04:50
Same problem
CentOS Linux release 7.6.1810 (Core) 
PHP 7.2.20
Web Server: Litespeed

**Comment by martindrapeau** [comment] 2019-11-12 06:20
Same problem on Windows.

**Comment by mikemike** [comment] 2020-06-05 12:05
This is still an issue for me, which is totally fixable by changing `fread` to `fgets`.  Will create a PR
