### ISSUE TITLE
[Proposal] Make updateMedia() accept UploadedFiles

### ISSUE THREAD

**Issue by lorisleiva** [spatie/laravel-medialibrary#1376] opened 2019-02-01 09:42 UTC
Hi there 👋 

First of all, thanks for this awesome library. ❤️ 

I particularly love the `updateMedia`. Before I used to implement the `removeMediaItemsNotPresentInArray` over and over on my projects.

However I often need to provide some new media (freshly uploaded) to this array. So I'll end up with a mixture of existing and non-yet-persisted media.

Currently I achieve this by mapping the `newMedia` array before sending it to the `updateMedia` method. Like this:

```php
public function syncMedia(array $media, $collection = 'default')
{
    $media = $this->mapWithUploadedMedia($media, $collection);
    return $this->updateMedia($media, $collection);
}

protected function mapWithUploadedMedia(array $media, $collection = 'default')
{
    return collect($media)->map(function ($medium) use ($collection) {
        if (! $medium instanceof UploadedFile) {
            return $medium;
        }

        return $this->addMedia($medium)->toMediaCollection($collection);
    })->toArray();
}
```

This could also be achieved directly in the `updateMedia` method by adding an extra conditional in the map closure. Obviously if I'm the only one who thinks this would be a good addition then there's no point adding this but just thought I'd give it a shot.

Thanks again for your work on this package (and all the others) 🙂

**Comment by Akhibemudu** [comment] 2019-03-15 00:56
@lorisleiva seems ur use case solved my current need. Here is my scenario; I created a Property form that accepts multiple property images which work well, but the problem is when trying to update that Property Model to accepts more image whenever the user clicks on update form,  Nothing happens, the only solvable scenario am left with, is to delete the existing media before adding new media. Which is wrong for my use case. Please, can I see your updateMedia  Method? Thank you.

**Comment by Akhibemudu** [comment] 2019-03-15 01:01
**Here is my UpdatePropertyForm**
`   foreach ($request->file('property_photos', []) as $key => $file) {
            $property->media->each->delete();
            $property->addMedia($file)
                ->preservingOriginal()
                ->toMediaCollection('property_image');
        }
`
For this, I want to add more images to the existing image in the Property Model without having to delete previous uploaded image ,,,

**Comment by lorisleiva** [comment] 2019-03-15 10:21
Hi there. It's a bit subjective because I have a `Media` resource class that defines how I want to provide the media to my frontend but here it is:

```php
<?php

namespace App\Concerns;

use App\Http\Resources\Media;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Collection;
use Spatie\MediaLibrary\Exceptions\MediaCannotBeUpdated;

trait SyncMedia
{
    public function syncMedia(array $newMediaArray, array $keepMediaArray = [], string $collectionName = 'default'): Collection
    {
        $newMediaArray = array_filter($newMediaArray);
        
        $this->removeMediaNotInArray(array_merge($newMediaArray, $keepMediaArray), $collectionName);
        
        return collect($newMediaArray)
            ->map(function ($newMedium) use ($collectionName) {
                static $orderColumn = 1;

                if ($newMedium instanceof UploadedFile) {
                    $currentMedium = $this->addMedia($newMedium)->toMediaCollection($collectionName);
                    $currentMedium->update([ 'order_column' => $orderColumn++ ]);
                    return $currentMedium;
                }

                $mediaClass = config('medialibrary.media_model');
                $currentMedium = $mediaClass::findOrFail($newMedium['id']);

                if ($currentMedium->collection_name !== $collectionName) {
                    throw MediaCannotBeUpdated::doesNotBelongToCollection($collectionName, $currentMedium);
                }

                if (array_key_exists('name', $newMedium)) {
                    $currentMedium->name = $newMedium['name'];
                }

                if (array_key_exists('custom_properties', $newMedium)) {
                    $currentMedium->custom_properties = $newMedium['custom_properties'];
                }

                $currentMedium->order_column = $orderColumn++;
                $currentMedium->save();
                return $currentMedium;
            })
            ->mapInto(Media::class);
    }

    protected function removeMediaNotInArray(array $array, string $collectionName = 'default')
    {
        $idsToKeep = collect($array)
            ->reject(function ($medium) {
                return $medium instanceof UploadedFile;
            })
            ->pluck('id')
            ->unique()->values()->toArray();

        $this->getMedia($collectionName)
            ->reject(function ($medium) use ($idsToKeep) {
                return in_array($medium->id, $idsToKeep);
            })
            ->each->delete();
    }
}
```

I hope this helps. 🍀

**Comment by Akhibemudu** [comment] 2019-03-16 09:17
Please @lorisleiva  are u using a custom Media Class with this trait?

**Comment by lingotacro** [comment] 2019-05-13 13:06
in my cas i can not update medias but i  can wreat using `addMedias` method

**Comment by brendt** [comment] 2019-07-15 14:07
Feel free to submit a tested PR for this. I'll be closing this issue and we'll continue the conversation in the PR.

**Closed by brendt** 2019-07-15 14:07 UTC
