### ISSUE TITLE
don't delete images in Storage I m a user of Laravel-media library v 9.12.4 with Nova 3 

### ISSUE THREAD

**Issue by mostafasamirs** [spatie/laravel-medialibrary#3272] opened 2023-05-30 16:30 UTC
I don't want to delete photos -  in Storage I m a user of Laravel-media library v 9.12.4 with Nova 3

**Comment by damianhrabaszcz** [comment] 2023-06-03 18:39
Can you provide more context to reproduce the issue?

**Comment by mostafasamirs** [comment] 2023-06-05 21:11
I have the code 
  public function registerMediaCollections(): void
    {
        $this->addMediaCollection(MediaHelper::TOUR_MEDIA_PATH)->singleFile();
        $this->addMediaCollection(MediaHelper::TOUR_GALLERY_MEDIA_PATH);
    }
    
    public function registerMediaConversions(Media $media = null): void {
        $this->addMediaConversion('webp')
            ->performOnCollections(MediaHelper::TOUR_MEDIA_PATH , 
             MediaHelper::TOUR_GALLERY_MEDIA_PATH)
            ->format(Manipulations::FORMAT_WEBP)
            ->width(500)
            ->height(350);
    }
    _______________________________
    Save the images Existing in the storage when the record is deleted from the data. I want 
    to save the images when the record is deleted from the database.
    ______________________________

**Comment by fredsal** [comment] 2023-06-06 19:02
Duplicate of https://github.com/spatie/laravel-medialibrary/discussions/3274
Duplicate of https://github.com/spatie/laravel-medialibrary/discussions/3273

**Comment by mostafasamirs** [comment] 2023-06-07 17:45
I want when I work to replace the file The old image is saved and a new created. ??

**Closed as completed** 2023-06-29 07:20 UTC
