### ISSUE TITLE
Method Spatie\MediaLibrary\MediaCollections\Models\Collections\MediaCollection::setCustomProperty does not exist.

### ISSUE THREAD

**Issue by krutsednar** [spatie/laravel-medialibrary#3069] opened 2022-10-23 03:33 UTC
### Discussed in https://github.com/spatie/laravel-medialibrary/discussions/3068

<div type='discussions-op-text'>

<sup>Originally posted by **krutsednar** October 23, 2022</sup>
```
$loiItem = Media::where('model_id',$user->id)->where('collection_name', 'applicant_user_letter')->get();
$loiItem->setCustomProperty('zip_filename_prefix', 'users/'.$user->code.'/user_letter'); 
$loiItem->save();

$mediaStream =  MediaStream::create($user->code.'.zip');
$mediaStream->addMedia($loiItem);
```

I'm trying to create a subfolder in my zip but it throws an error
**Method Spatie\MediaLibrary\MediaCollections\Models\Collections\MediaCollection::setCustomProperty does not exist.**
</div>

**Comment by freekmurze** [comment] 2022-10-23 08:50
Duplicate of discussion

**Closed** 2022-10-23 08:51 UTC
