### ISSUE TITLE
Collections/Conversions weird behaviour, last one wins

### ISSUE THREAD

**Issue by mlusetti** [spatie/laravel-medialibrary#119] opened 2015-12-07 10:31 UTC
Take this code:

```php
$prod = Prodocuts::findOrFail($id);

$prod->clearMediaCollection('tech');
$prod->addMedia($techFile)
                        ->withCustomProperties([
                            'slug' => $prod->getTranslation('en')->slug,
                        ])
                        ->preservingOriginal()
                        ->toCollection('tech');
$prod->save();

$prod->clearMediaCollection('images');
$prod->addMedia($imageFile)
                        ->withCustomProperties([
                            'slug' => $prod->getTranslation('en')->slug,
                        ])
                        ->preservingOriginal()
                        ->toCollection('images');
$prod->save();
```

With $prod implementing HasMediaConversions as

```php
public function registerMediaConversions()
    {
        $this->addMediaConversion('thumb')
            ->setManipulations(['w' => 510, 'h' => 510])
            ->performOnCollections('images');
    }
````

I've got only the last file in the filesystem but (correctly) two entries in the DB.

I think I've checked almost everything.
I'm using a custom path generator which is leveraging the "slug" custom property to generate the path.
The conversion are working fine (for the file which ends in the filesystem). They don't take in account the performOnCollection calls. If I do only the addMedia toCollection('tech') call it is producing a thumb from the tech pdf file.
 
One thing to not is that this is a sailent fail, every code line is passing without any errors.

I think I'm not doing anything wrong here.

Any hint is appreciated.

**Comment by sebastiandedeyne** [comment] 2015-12-07 11:42
So if I understand your issue, everything goes well in the database, but you're missing one of your media files on the filesystem?

Could you post a snippet of your custom path generator?

**Comment by mlusetti** [comment] 2015-12-07 12:01
Yep. Here it is, just the getBasePath function:

```php
        $modelNamePath = explode('\\', $media->model_type);

        $modelName = $modelNamePath[count($modelNamePath) - 1];

        $slug = $media->getCustomProperty('slug', 'default-images');
        
        return str_slug($modelName) . '/' . $slug;
````

The path is correctly generated for each model (tested).

Thanks for your comment.

**Comment by sebastiandedeyne** [comment] 2015-12-07 13:05
Aren't you generating two identical paths that way? I'd think your second media file is overwriting your first one on the filesystem.

Both `model_type` and the `slug` custom property will be the same, so you're generating equal file paths.

**Comment by mlusetti** [comment] 2015-12-07 14:17
Not at all, the files have different names. But yes, I would like to have them all in the same directory.

Are you telling me that clearMediaCollection('collectionname') will delete every files in every collection?

**Comment by mlusetti** [comment] 2015-12-07 15:06
Ah, just noticed my typo in the title, thanks for clarifying.

**Comment by sebastiandedeyne** [comment] 2015-12-07 20:39
Hmm no `clearMediaCollection` only deletes files for a certain model.

Some more debugging ideas: 

- If you do `images` first and then `tech`, is it the same one that doesn't save?
- Do you have the same issue using the default path generator?

**Comment by mlusetti** [comment] 2015-12-09 08:18
Hi @sebastiandedeyne ,
  thanks for your time.

Any order I use the last one is the only one saved.

Never tried the default path generator. Should I try it? How could the path generator could go wrong if it saves correctly at least one file?

Cheers

**Comment by freekmurze** [comment] 2015-12-10 18:42
I'm looking at your original code snippet. Could you please try again clearing both mediacollections first and without the first call `$prod->save();`?

**Comment by mlusetti** [comment] 2015-12-11 08:41
The call seems to not cause any different behavior, but testing it I've saw something I didn't noticed before.

If the destination path is not present in the disk, say is the first time for a new $prod everything is working correctly. The pdf and jpg goes in the correct directory and the thumb is generated for the images collection.

The second time the function is called, say when the user update the $prod instance with a new image and a new pdf, only the last one ends up in the filesystem. The first one is lost.

Did this rings any bells?

**Comment by mlusetti** [comment] 2015-12-11 08:44
Sorry I made confusion.

The different behavior is made if the entry is in the db or not. If there's no entry in the db everything is working as expected, if there's already and entry in the media table for the current $prod only the last one is saved in the filesystem.

Did I made it clear?

**Comment by freekmurze** [comment] 2015-12-11 09:25
I'm not sure if I understand you correctly.

Could you try adding:
`$prod = Prodocuts::findOrFail($id);`
after the first save?

I'm thinking maybe your problem has something to do with the relations that eloquent is keeping on the model.

**Comment by mlusetti** [comment] 2015-12-11 13:46
No change. Only the last one succeed in the filesystem but in the db I got all the entries.

**Comment by mlusetti** [comment] 2015-12-20 15:36
Any news on this one ?

I've used a workaround, which consists in storing in different path based on "type" of the media, but I find this behavior pretty limiting when you need or want to handle multiple files for each model.
So I add a type custom properties to each media (say type => 'pdf' or type => 'images') and in the path generator I use this property, as I've done with the slug one, to add a directory beneath the main one.

If you would like to see the full code snippet I can give it to you.

Cheers.

**Comment by freekmurze** [comment] 2016-01-25 16:27
I'm going to close this for now as:
-  we couldn't reproduce this
- no other users have run into this problems
- you found a workaround

If this problem bites any other user, please reopen.

**Closed by freekmurze** 2016-01-25 16:27 UTC
