### ISSUE TITLE
Docs misleading when using custom UrlGenerator

### ISSUE THREAD

**Issue by mikemand** [spatie/laravel-medialibrary#400] opened 2016-11-17 22:37 UTC
The docs state:

> If you'd extend `Spatie\MediaLibraryUrlGenerator\BaseGenerator` you only need to implement one method: `getUrl`, which should return the URL.

However, when using `$model->getFirstMediaPath('collection')` I got the following exception:

```
FatalThrowableError in Media.php line 85:
Call to undefined method App\Custom\MediaLibrary\UrlGenerator::getPath()
```

The `UrlGenerator` interface does not have a `getPath()` method and `Spatie\MediaLibrary\UrlGenerator\BaseUrlGenerator` (which is what I assume the docs meant I should extend, instead of the nonexistent `Spatie\MediaLibraryUrlGenerator\BaseGenerator` - or even `Spatie\MediaLibrary\UrlGenerator\BaseGenerator`) also does not have this method.

`Spatie\MediaLibrary\UrlGenerator\LocalUrlGenerator` _does_ have a `getPath()` method, so I was able to figure out how I needed to write my own. `Spatie\MediaLibrary\UrlGenerator\S3UrlGenerator` does not have a `getPath()`, but I assume that has something to do with it being a remote filesystem that is only accessible (to the end user) via HTTP(S).

**Comment by Jasper9041** [comment] 2017-02-02 14:03
I have created a PR that fixes these errors in the documentation. https://github.com/spatie/docs.spatie.be/pull/112

I believe the errors you are having are indeed caused by the use of getPath() in combination with a Non-local driver. This issue describes your problem: https://github.com/spatie/laravel-medialibrary/issues/464
I can't speak for @freekmurze but I think this issue should no longer occur in v5 if issue 464 gets fixed.

**Comment by freekmurze** [comment] 2017-02-02 14:12
I'll make sure #464 will be addressed in `v5`.

**Closed by freekmurze** 2017-02-02 14:12 UTC

**Comment by mikemand** [comment] 2017-02-02 18:48
Thank you!
