### ISSUE TITLE
Issue with trait method updateMedia()

### ISSUE THREAD

**Issue by ModestasV** [spatie/laravel-medialibrary#816] opened 2017-10-25 08:00 UTC
Hello,

Noticed a bug with: `\Spatie\MediaLibrary\HasMedia\HasMediaTrait::updateMedia()` function:
When calling it, you need to pass an array which is alright but on the return - the array gets converted to collection and then mapped. Issue is that the map asks for array too but receives a collection... 

The problematic code:

```
return collect($newMediaArray)
            ->map(function (array $newMediaItem) use ($collectionName) {
```
Which produces this error: http://prntscr.com/h1prsz

Possible solution:
Change the type hinting to: 
```
  return collect($newMediaArray)
            ->map(function (Media $newMediaItem) use ($collectionName) {
```
Where media is a: `Spatie\MediaLibrary\Media`

Hope that this error report is clear, if not - i'll add more details as needed.

**Comment by freekmurze** [comment] 2017-10-25 08:11
The tests seem to indicate that `updateMedia` is working as intended. Could you PR a failing test to `UpdateMediaTest.php`?

**Comment by ModestasV** [comment] 2017-10-25 09:36
Right, while doing tests I've found a case where it fails - in tests it's passing an array of the data instead of the instace. 
Failing code:
```
        $mediaArray = $this->testModel->getMedia('collection');
```
Non failing code:
```
        $mediaArray = $this->testModel->getMedia('collection')->toArray();
```

So, the next question - do you want a PR with an ability to accept model instances, instead of just array? :)

**Comment by freekmurze** [comment] 2017-10-25 10:36
Ideally it should accept a model instance, a collection of model instances and an array of model instances.

**Comment by ModestasV** [comment] 2017-10-25 10:44
Yap, that is what I've encountered - array of model instances were not working out for me :) Will make a PR for you ;)

**Comment by freekmurze** [comment] 2017-10-25 11:31
👍 

Closing this for now and looking forward to the PR.

**Closed by freekmurze** 2017-10-25 11:31 UTC
