### ISSUE TITLE
Class name must be a valid object or a string on deploy

### ISSUE THREAD

**Issue by joostvanhoof** [spatie/laravel-medialibrary#2250] opened 2021-01-07 10:05 UTC
Since switching from Forge to Envoyer (blog post to follow ;-)) I get this error every time I deploy `Class name must be a valid object or a string`. I know that screenshots are not very helpful but this is all I can share from my error monitoring. Please let me know if you need additional details.

<img width="702" alt="Screenshot 2021-01-07 at 11 02 54" src="https://user-images.githubusercontent.com/5268113/103879468-3195f000-50d8-11eb-9d87-f9b53ee16cbc.png">

**Comment by freekmurze** [comment] 2021-01-17 14:53
I can't reproduce this and the tests of this package are running fine.

I'm thinking that this is caused by something in your environment. 

Make sure you  are clearing the config cache while deploying.

Could you maybe create a minimal example in which you reproduce the issue?

**Comment by joostvanhoof** [comment] 2021-01-18 11:03
Thanks. I'm clearing the config cache during deployment. It's a little difficult to create a minimal example, it only happens when I deploy to prod (via Envoyer but I'm sure that doesn't matter) so I wouldn't know how to reproduce this locally. If this puts this issue in a place where it's difficult to move ahead then I propose we just close it.

**Comment by freekmurze** [comment] 2021-01-18 11:14
Closing for now, as this is probably caused by a configuration issue at your end.

If you find the root cause, please let me know in this issue. Might be helpful for others.

**Closed by freekmurze** 2021-01-18 11:14 UTC

**Comment by shalvah** [comment] 2021-02-14 11:22
Had the same issue happen on prod only as well (with Forge). Turned out [this](https://github.com/spatie/laravel-medialibrary/issues/1988#issuecomment-680931010) fixed it for me.

Eventual solution: add `php artisan cache:clear` to your deploy script *before* `composer install`.
