### ISSUE TITLE
 I need to determine the type of file to download in media library, it does not work, here are my codes

### ISSUE THREAD

**Issue by danielshongo** [spatie/laravel-medialibrary#1515] opened 2019-07-31 08:52 UTC
public function registerMediaCollections()
{
    $this->addMediaCollection('slider')
     ->acceptsFile(function (File $file) {
            return $file->mimeType === 'image/jpeg';
        });

}

**Comment by freekmurze** [comment] 2019-07-31 09:15
I don't understand what you are trying to achieve...

**Comment by danielshongo** [comment] 2019-07-31 10:20
I wishv to use Only allow certain files in a collection, but it not working
that is my code
hp

namespace App;

use Illuminate\Notifications\Notifiable;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\File;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements HasMedia
{
    use Notifiable,HasMediaTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function registerMediaCollections()
{
    $this->addMediaCollection('slider')
     ->acceptsFile(function (File $file) {
           dd('fdd');
            return $file->mimeType === 'image/jpeg';
        });

}
}

**Comment by danielshongo** [comment] 2019-07-31 10:21
sorry that is my code

hp

namespace App;

use Illuminate\Notifications\Notifiable;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\File;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements HasMedia
{
    use Notifiable,HasMediaTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function registerMediaCollections()
{
    $this->addMediaCollection('slider')
     ->acceptsFile(function (File $file) {
            return $file->mimeType === 'image/jpeg';
        });

}
}

Le mer. 31 juil. 2019 à 12:19, Daniel Shongo <danielshongo2013@gmail.com> a
écrit :

>
> I wishv to use Only allow certain files in a collection, but it not
> working
> that is my code
> hp
>
> namespace App;
>
> use Illuminate\Notifications\Notifiable;
> use Spatie\MediaLibrary\HasMedia\HasMedia;
> use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
> use Spatie\MediaLibrary\File;
> use Illuminate\Foundation\Auth\User as Authenticatable;
>
> class User extends Authenticatable implements HasMedia
> {
>     use Notifiable,HasMediaTrait;
>
>     /**
>      * The attributes that are mass assignable.
>      *
>      * @var array
>      */
>     protected $fillable = [
>         'name', 'email', 'password',
>     ];
>
>     /**
>      * The attributes that should be hidden for arrays.
>      *
>      * @var array
>      */
>     protected $hidden = [
>         'password', 'remember_token',
>     ];
>
>     public function registerMediaCollections()
> {
>     $this->addMediaCollection('slider')
>      ->acceptsFile(function (File $file) {
>            dd('fdd');
>             return $file->mimeType === 'image/jpeg';
>         });
>
> }
> }
>
> Le mer. 31 juil. 2019 à 11:15, Freek Van der Herten <

**Comment by brendt** [comment] 2019-08-02 09:46
I suppose this is a duplicate of #1516 ? I'll be closing this issue for now and we'll continue the conversation in #1516

**Closed by brendt** 2019-08-02 09:46 UTC
