### ISSUE TITLE
vendor:publish views does not actually publish the views for responsive images

### ISSUE THREAD

**Issue by beartas** [spatie/laravel-medialibrary#989] opened 2018-03-23 09:43 UTC
https://docs.spatie.be/laravel-medialibrary/v7/responsive-images/customizing-the-rendered-html
```
php artisan vendor:publish --provider="Spatie\MediaLibrary\MediaLibraryServiceProvider" --tag="views"
```
Looks like...
```
$this->publishes([
       __DIR__.'/../resources/views' => resource_path('views/vendor/medialibrary'),
    ], 'views');
```
may be missing from MediaLibraryServiceProvider@boot method

**Comment by clarkewing** [comment] 2018-03-23 11:02
Duplicate of #964

**Comment by beartas** [comment] 2018-03-23 11:13
[#964](url) is closed although the fix hasn't made it into the master branch

**Comment by freekmurze** [comment] 2018-03-23 12:19
Forgot to push it, the fix is in the latest version now.

**Closed by freekmurze** 2018-03-23 12:19 UTC

**Comment by beartas** [comment] 2018-03-23 13:00
Merci beaucoup
