### ISSUE TITLE
clearMediaCollection don`t delete files if custom_path_generator_class used

### ISSUE THREAD

**Issue by GriPower** [spatie/laravel-medialibrary#656] opened 2017-06-11 08:15 UTC

**Comment by freekmurze** [comment] 2017-06-11 09:14
Please PR a failibg test

**Comment by fetzi** [comment] 2017-06-19 09:21
@freekmurze tried to reproduce the issue but files get deleted correctly.

**Comment by freekmurze** [comment] 2017-06-19 14:47
Closing this because the problem can't be reproduced.

**Closed by freekmurze** 2017-06-19 14:47 UTC
