### ISSUE TITLE
Target [Spatie\MediaLibrary\UrlGenerator\UrlGenerator] is not instantiable

### ISSUE THREAD

**Issue by inov** [spatie/laravel-medialibrary#63] opened 2015-09-23 13:40 UTC
I get this error after installing the package through composer. Seems like the UrlGenerator Interface can't be resolved from the App Container. Anyone else experiencing this? How can I fix this?
The error occurs when calling getUrl() on a Media object.

<pre>
ErrorException in Container.php line 744:
Target [Spatie\MediaLibrary\UrlGenerator\UrlGenerator] is not instantiable.
</pre>

**Comment by freekmurze** [comment] 2015-09-23 13:48
Did you install the service provider? Does `config('laravel-medialibrary.custom_url_generator_class')` point to a valid class?

**Comment by inov** [comment] 2015-09-23 14:09
I do include the ServiceProvider. The custom_url_generator_class is blank because my files are stored locally:

<pre>
    /*
     * When urls to files get generated this class will be called. Leave empty
     * if your files are stored locally above the site root or on s3.
     */
    'custom_url_generator_class' => '',

</pre>

**Comment by freekmurze** [comment] 2015-09-23 14:44
Have you added a disk named "media" in `app/config/filesystems.php`?
More info in the [installation instructions](https://github.com/spatie/laravel-medialibrary#installation).

**Comment by inov** [comment] 2015-09-23 14:50
yes did that as well. When I add the line below to my ServiceProvider booting method, the Error goes away, but is followed by another error.

<pre>
$this->app->bind(UrlGenerator::class, LocalUrlGenerator::class);
</pre>

and the error:

<pre>
ErrorException in Arr.php line 152:
Invalid argument supplied for foreach() 
</pre>

**Comment by freekmurze** [comment] 2015-09-23 14:56
Can you check what is the value of `$urlGeneratorClass` on this line: https://github.com/spatie/laravel-medialibrary/blob/master/src/UrlGenerator/UrlGeneratorFactory.php#L19 ?

**Comment by freekmurze** [comment] 2015-09-29 08:20
Did you find a solution for this issue?

**Comment by freekmurze** [comment] 2015-10-01 22:07
I'm going to close this for now. If you have any further problems let me know. I'd appreciate if you could add your solution to this issue. It might be helpful for others.

**Closed by freekmurze** 2015-10-01 22:07 UTC

**Comment by thijsdemaa** [comment] 2015-12-29 17:36
I too had this issue and it was caused by a mistake of my own. I had used route model binding to get to the Media class, however in this particular route i had used a different identifier. Therefor only the ID (1) was being given, and the type-hinted Media object in my controller had exist => false.
