### ISSUE TITLE
New single file image is deleted when replaced..

### ISSUE THREAD

**Issue by ambengers** [spatie/laravel-medialibrary#1337] opened 2018-12-18 05:26 UTC
Here's the codes from my test, last assertion does not work

```
/** @test */
public function initial_banner_is_deleted_when_banner_is_updated()
{
        $packer = factory(Packer::class)->create(['serial_number' => 'Packer ABC', 'company_id' => $this->user->company_id]);

        $oldBanner = UploadedFile::fake()->image('sample-image.jpg');

        $packer->addBanner($oldBanner);

        Storage::disk('public')->assertExists('packer/' . $packer->id . '/banner/' . $oldBanner->hashName());

        $newBanner = UploadedFile::fake()->image('sample-image-2.jpg');

        $packer->addBanner($newBanner);

        // Assert that old banner is now missing..
        $this->assertDatabaseMissing('media', [
            'model_type'        =>  'packer',
            'model_id'          =>  $packer->id,
            'collection_name'   =>  'banner',
            'file_name'         =>  $oldBanner->hashName(),
        ]);

        Storage::disk('public')->assertMissing('packer/' . $packer->id . '/banner/' . $oldBanner->hashName());

        // Assert that new banner has been stored..
        $this->assertDatabaseHas('media', [
            'model_type'        =>  'packer',
            'model_id'          =>  $packer->id,
            'collection_name'   =>  'banner',
            'file_name'         =>  $newBanner->hashName(),
        ]);

        // THIS ASSERTION BELOW IS FAILING SINCE THE NEW BANNER WAS DELETED
        Storage::disk('public')->assertExists('packer/' . $packer->id . '/banner/' . $newBanner->hashName());
}
```

Here's the addBanner code on Packer model..
```
public function addBanner(UploadedFile $image = null)
{
        return $image ?
            $this
                ->addMedia($image)
                ->usingFileName($image->hashName())
                ->toMediaCollection('banner') : null;
}
```

Here's how I registered the banner collection on Packer model..
```
public function registerMediaCollections()
{
        // Banner image
        $this->addMediaCollection('banner')->singleFile();
}
```

**Comment by freekmurze** [comment] 2019-01-02 16:35
That call to `singleFile()` signals the package that it should empty the collection when something is added to it. If you don't want this behaviour, remove that call.

**Comment by ambengers** [comment] 2019-01-03 01:07
@freekmurze thanks for your response! I think that's the intended behavior. The only problem is that when new media is added it also deletes the recently added file, which is odd. 

Shouldn't the flow when new media is added be like delete all items in the collection except the most recent?

**Comment by freekmurze** [comment] 2019-01-03 09:16
Mmm, that's odd indeed. The tests of this package prove that the feature is working as intended. Could you PR a failing test for me to look at?

**Comment by anouarabdsslm** [comment] 2019-01-07 12:41
@freekmurze Im experiencing exact the same issue when replacing an image using `singleFile` option, the record for the replaced image media still exists on media table but the related file get removed.

**Comment by freekmurze** [comment] 2019-01-07 19:16
Duplicate of #1273 

We'll tackle it in that issue.

**Closed by freekmurze** 2019-01-07 19:16 UTC
