### ISSUE TITLE
MediaObserver is not being registered

### ISSUE THREAD

**Issue by Namoshek** [spatie/laravel-medialibrary#1575] opened 2019-09-25 11:47 UTC
Package | Version
---------|----------
`laravel/framework` | 6.0.3
`spatie/laravel-medialibrary` | 7.14.0

I'm running into a very strange issue that I have never ever noticed anywhere else so far. For some reason, the `MediaObserver` is not being registered. Both, `register()` and `boot()` of the `MediaLibraryServiceProvider` are executed properly (verified via some added logs and by fetching a bound class from the service container). The observer registration is executed (again, verified via logs)

https://github.com/spatie/laravel-medialibrary/blob/af0505b7e1f4c5c92b616aa30e5253f2c98fc647/src/MediaLibraryServiceProvider.php#L31-L33

but there are no listeners being registered in the dispatcher:

```php
>>> $d = app(\Illuminate\Contracts\Events\Dispatcher::class)
=> Illuminate\Events\Dispatcher {#550}
>>> dump($d->getListeners('eloquent.deleted: Spatie\MediaLibrary\Models\Media'))
array:2 [
  0 => Closure($event, $payload)^ {#521
    class: "Illuminate\Events\Dispatcher"
    this: Illuminate\Events\Dispatcher {#36 …}
    use: {
      $listener: array:2 [
        0 => Laravel\Telescope\Watchers\EventWatcher^ {#522
          +options: []
        }
        1 => "recordEvent"
      ]
      $wildcard: true
    }
    file: "./vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php"
    line: "342 to 348"
  }
  1 => Closure($event, $payload)^ {#533
    class: "Illuminate\Events\Dispatcher"
    this: Illuminate\Events\Dispatcher {#36 …}
    use: {
      $listener: array:2 [
        0 => Laravel\Telescope\Watchers\ModelWatcher^ {#534
          +options: array:2 [
            "enabled" => true
            "events" => array:1 [
              0 => "eloquent.*"
            ]
          ]
        }
        1 => "recordAction"
      ]
      $wildcard: true
    }
    file: "./vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php"
    line: "342 to 348"
  }
]
=> [
     Closure($event, $payload) {#521 …5},
     Closure($event, $payload) {#533 …5},
   ]
```

_I kept the Telescope listeners enabled on purpose to demonstrate that event listener registration does indeed work (at least for other packages and application specific listeners)._

I did _fix_ the issue by creating a second service provider in my application namespace which uses the exact same code to register the model observer as shown above. I have not the slightest idea why this works though, as the other service provider is executed as well and the code is literally the same.

NB: I'm using a stock installation of the media library (except for a custom storage disk). None of the package classes are overwritten by me and I'm **not** using a custom `Media` model as described in #1392.

I've now tried pretty much everything that comes to my mind, so I'm entirely out of ideas what could cause this behavior. Any help is appreciated!

**Comment by tnorthcutt** [comment] 2019-09-25 18:54
It looks like maybe this is related to https://github.com/spatie/laravel-medialibrary/issues/1567, perhaps?

**Comment by Namoshek** [comment] 2019-09-25 19:33
Not getting any installation errors, so I'd probably say no. Actually, I'm not getting any error at all, just not the desired behavior either.

**Comment by tnorthcutt** [comment] 2019-09-25 22:02
@Namoshek Ok, thanks for letting me know.

**Comment by rubenvanassche** [comment] 2019-10-04 11:07
Hi @Namoshek,

I couldn't reproduce your issue in a clean Laravel installation.

Can you verify if the `MediaLibraryServiceProvider` is registered? If so can you check what's in the `$mediaClass` variable in `MediaLibraryServiceProvider`? Since we're calling `$mediaClass::observe(new MediaObserver());` there which handles the control over to the Laravel Framework(https://laravel.com/docs/5.8/eloquent#observers). That's the only point where something can go wrong with our package, after that Laravel is handling everything.

**Comment by Namoshek** [comment] 2019-10-04 21:16
Hi @rubenvanassche,

thanks for asking. Yes, the service provider is registered and the `$mediaClass` variable contains the correct FQCN `Spatie\MediaLibrary\Models\Media`. Execution of the service provider is also flawless (I debugged the execution and it looks fine; I also added log statements before and after the `$mediaClass::observe(new MediaObserver())` statement and there is no issue there either). So yeah, I've no clue what's going wrong.

I actually don't expect this to be an issue with your package directly. Didn't really expect it to get much attention at all. I simply hoped someone else experiences the same (not that I wish anyone issues with their code) and would see and confirm this. But seems it's on me or my project.

**Comment by rubenvanassche** [comment] 2019-10-16 12:10
Hi @Namoshek,

I'm sorry I can't help you. You could maybe try to install the media library in a clean Laravel installation on your system. If it still fails there's maybe something wrong with the configuration of your system?

Good luck!

I will close this issue for now, feel free to reopen it if you have a new lead!

**Closed by rubenvanassche** 2019-10-16 12:10 UTC

**Comment by sveen** [comment] 2021-02-06 22:44
Remove files in bootstrap directory . Then run composer dump-autoload. After try to install(require)
 again.
