### ISSUE TITLE
Undefined index: base64svg

### ISSUE THREAD

**Issue by hatcham** [spatie/laravel-medialibrary#967] opened 2018-03-20 21:31 UTC
Version 7:

If you happen to try and load a page containing a responsive image that has not fully been processed in the queue, by that I mean, processing has begun but has not completed, the following exception is thrown:

Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Undefined index: base64svg (View: /home/forge/tfh-manuals.hatcham.com/vendor/spatie/laravel-medialibrary/resources/views/responsiveImageWithPlaceholder.blade.php)

So before the job has been processed has run I get the normal <img> tag with a single image. After the job has been processed I get the <img> tag with full srcset. This error occurs in between. 

It is a bit of an edge case but has popped up on more than one occasion today.

I'd love to send a PR but I don't know where to start!

Brilliant package by the way, really enjoying using it. Thank you.

**Comment by brendt** [comment] 2018-03-21 12:42
Hi @hatcham 

This was a more complex issue to write a good test for, so I went ahead and made a PR myself. If you're interested in how the issue is fixed, you can check out the PR: #973

We'll merge this as soon as the review is done.

**Comment by brendt** [comment] 2018-03-21 13:46
Fixed in 7.0.3.

https://github.com/spatie/laravel-medialibrary/releases/tag/7.0.3

**Closed by brendt** 2018-03-21 13:46 UTC
